import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/layout/Header/Header";
// import Footer from "@/layout/Footer/Footer";
import { PageTransition, ScrollProgressBar } from "@/components/Animations";
import FooterBottom from "@/layout/FooterBottom/FooterBottom";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      dir="rtl"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ScrollProgressBar />
        <Header />
        {/* {children} */}
        <PageTransition>{children}</PageTransition>
        {/* {children} */}
        {/* <Footer /> */}
        <FooterBottom />
      </body>
    </html>
  );
}
